print ("corona Circular")
radio_ma =float(input("Ingrese Radio mayor"))
radioe_me =float(input("Ingrese radio menor"))
area = 3.14* (radio_ma**2 - radio_me**2)
print ("resultados")
print("Area:",area)
